### PR TITLE
Cleaned and Ordered data sets

### PR DESCRIPTION
**Pull request by bvanev**
cleaned UTF-* encoded data to prevent the need for additional processing, resulting in clean display of text when rendered in all browsers other than Chrome on MacOS and Windows

Data ordered by 1.'Company' 2.'diameter_in' in projectiles.json and projectiles.csv

Data order by 'diameter_in' in {company}.json and {company}.csv files

### CODE REVIEW

**Comment by erichiggins** [comment]
Thanks for the PR, @bvanev !!

### Unicode characters
Since the display issue was an HTML bug, is it still necessary to remove the unicode characters?  Perhaps the files could be duplicated with ascii-only copies for those who require them (e.g. `projectiles_ascii.csv` and `sierra_ascii.csv`)?

### Data ordering
As mentioned in the README, it's quite impractical to order and structure the data in a way that works for every use-case.   That said, here's what I'd suggest:

#### `projectiles.*`
Order by
1. type
2. company
3. diameter
4. weight
5. sku (if needed)

#### `<company>.*`
Order by
1. type
2. diameter
3. weight
4. sku (if needed)

**Comment by bvanev** [comment]
### Unicode Characters
I will add the characters back into the data sets.  I agree that there is no need to remove them.

### Data Ordering
I will also order per your suggestion.  I agree that it is difficult to meet every use case.  Anything other than this can be managed by the consumer of the data sets.

Once these items are done, I will submit a new pull request.

**Comment by erichiggins** [comment]
Hey @bvanev , just resurfacing this in your inbox.  Are you planning on making the changes to this PR or creating a new one?  Thanks again for the suggestions and contribution!

**Comment by erichiggins** [comment]
@bvanev Ping 👋

**Comment by erichiggins** [comment]
Closing for now since it appears to be abandoned and the ordering issue has been fixed in #8

**Pull request closed without merging**
