### PR TITLE
Fix order in JSON datasets. 

### LINKED ISSUE #7: Fix ordering
Fix ordering per @erichiggins suggestions in https://github.com/ammolytics/projectiles/pull/6

### PR DESCRIPTION
**Pull request by GAO8A**
Fixes ordering per https://github.com/ammolytics/projectiles/pull/6#issuecomment-401443747

I used https://github.com/zemirco/json2csv#readme to convert the JSON to csv, but I can't seem to get the "bc_fn" column to display properly with it's quote configuration. @erichiggins what type of json to csv (or vice-versa) conversion tool did you use? Right now `projectiles.csv` contains double quotes but is properly formated.

Thanks

close #7

### CODE REVIEW

**Comment by erichiggins** [comment]
@GAO8A I don't remember off the top of my head, but most likely I treated the CSV files as the source-of-truth and generated the JSON from that data using the Python interactive console.  That said, [OpenRefine](http://openrefine.org/) is a super useful tool to have in your kit and can make sorting and spot-checking significantly easier.

I believe the double-quotes are optional and valid, but it may be useful to strip them just to help keep file sizes down as much as possible.

**Comment by GAO8A** [comment]
@erichiggins Added ordered csvs. `sierra.csv` and `projectiles.csv` still contain double quotes for above reasons

**Comment by erichiggins** [comment]
Great, thanks @GAO8A !

It can be challenging to review large changes like this. Is there anything in particular you'd like me to take a look at for verification?

**Comment by GAO8A** [comment]
@erichiggins Nothing in particular. Perhaps just a random scan on the ordering or floating points you know may need quotes in the CSV.

Thanks!

**Comment by erichiggins** [comment]
LGTM! Thanks!

**Review by erichiggins — COMMENTED** [review]
LGTM

**Pull request merged**
